import type { Metadata } from "next";
import "./globals.css";
import { cn } from '@/libs/utils';
import { fontHelvetica } from '@/libs/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontHelvetica.variable, 'font-helvetica')}>
  
        {children}
        
        </body>
    </html>
  );
}
